BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "course" (
	"_id"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT,
	PRIMARY KEY("_id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "lesson" (
	"_id"	INTEGER NOT NULL UNIQUE,
	"courseid"	INTEGER,
	"title"	TEXT,
	"section0"	TEXT,
	"section1"	TEXT,
	"section2"	TEXT,
	"section3"	TEXT,
	"section4"	TEXT,
	"section5"	TEXT,
	"section6"	TEXT,
	"section7"	TEXT,
	"section8"	TEXT,
	"section9"	REAL,
	"questions"	INTEGER,
	"result"	INTEGER DEFAULT 0,
	"nsections"	INTEGER DEFAULT 0,
	PRIMARY KEY("_id" AUTOINCREMENT)
);
INSERT INTO "course" VALUES (1,'Struktur Data Algoritma Pemrograman');
INSERT INTO "course" VALUES (2,'Bukan SDAP');
INSERT INTO "lesson" VALUES (1,1,'Tipe Data','Tipe Data<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.','Tipe Data<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'La password più usata degli ultimi anni è:<->123456<->Abcdef<->Qwerty123<->password<<-->>Esistono password davvero sicure?<->No, qualunque password può essere trovata in un tempo abbastanza lungo<->Sì, la mia lo è<->No, perché tutte le password sono già state utilizzate<->Si, ma nessuno ne ha mai trovata una<<-->>Gli attacchi dizionario tentano di indovinare le nostre password:<->liste di parole di uso comune<->Usando dizionari di varie lingue diverse<->Usando parole messe in ordine alfabetico, come in un dizionario<->Con parole generate a caso da un computer<<-->>Password Chart ci permette di:<->Generare password davvero sicure<->Accedere alle nostre password senza utilizzarne nessuna<->Attaccare gli account dei nostri contatti email<->Monitorare la sicurezza della nostra password<<-->>Affidare le password a un password manager è molto comodo e veloce, ma non molto sicuro<->F<<-->>Utilizzare caratteri MAIUSCOLI e minuscoli nella nostra password aumenta la sua resistenza agli attacchi<->T<<-->>È conveniente usare i nomi dei nostri familiari nelle nostre password, perché sono facili da ricordare e, dopotutto, non facili da indovinare da utenti esteri<->F<<-->>Password Chart è un sistema inutile e scoraggiante, perché genera password incomprensibili<->F<<-->>Per accedere al nostro password manager è necessario ricordare un’unica, lunga master key<->T<<-->>È fortemente consigliato cambiare la propria password dopo qualche mese di utilizzo<->T',0,2);
INSERT INTO "lesson" VALUES (2,1,'Deklarasi','Deklarasi<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.','Deklarasi<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,2);
INSERT INTO "lesson" VALUES (3,2,'Bukan','Bukan<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.','Bukan<<-->>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Posuere morbi leo urna molestie. Velit laoreet id donec ultrices tincidunt. Malesuada bibendum arcu vitae elementum curabitur. Fermentum iaculis eu non diam phasellus vestibulum. Et tortor consequat id porta nibh venenatis cras. Cras adipiscing enim eu turpis. Ultrices vitae auctor eu augue ut. Ut lectus arcu bibendum at varius vel. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Auctor neque vitae tempus quam pellentesque. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Purus sit amet luctus venenatis. Lacinia at quis risus sed vulputate odio ut.
Semper risus in hendrerit gravida rutrum quisque non. Non diam phasellus vestibulum lorem sed. Vel eros donec ac odio tempor orci dapibus ultrices. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Interdum varius sit amet mattis vulputate enim nulla. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Urna duis convallis convallis tellus id interdum. Cras adipiscing enim eu turpis egestas pretium aenean. Ultrices eros in cursus turpis massa tincidunt. Eu non diam phasellus vestibulum lorem sed risus ultricies. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Iaculis nunc sed augue lacus viverra vitae congue eu. Sit amet nisl suscipit adipiscing bibendum est ultricies. Quis blandit turpis cursus in hac habitasse platea.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,2);
COMMIT;
